#[phases.setup]
  aptPkgs = [
    "chromium-browser",
    "curl", "unzip", "jq",
    # ... all your other essential libraries from the previous version ...
    "libglib2.0-0", "libnss3", "libfontconfig1", "libx11-6", "libxcb1",
    "libxcomposite1", "libxrandr2", "libxrender1", "libxtst6", "ca-certificates",
    "fonts-liberation", "libasound2t64", "libatk-bridge2.0-0", "libatk1.0-0",
    "libcups2", "libdbus-1-3", "libgdk-pixbuf2.0-0", "libgtk-3-0",
    "libpango-1.0-0", "libpangocairo-1.0-0", "xdg-utils"
  ]
  cmds = [
    "echo 'SETUP_CMDS: Manually installing a specific Chromedriver version...'",
    
    # !!! USER ACTION: YOU MUST REPLACE THE LINE BELOW WITH A VALID CHROMEDRIVER URL !!!
    # 1. Go to: https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json
    # 2. Find a recent "Stable" version (e.g., for Chrome/Chromium 125 or 126).
    # 3. Copy the URL for the "chromedriver" -> "linux64" download.
    # Example (this URL will likely be outdated, VERIFY AND REPLACE IT FROM THE CFT JSON):
    "CHROMEDRIVER_URL='https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.76/linux64/chromedriver-linux64.zip'",
    
    "echo \"SETUP_CMDS: Downloading Chromedriver from ${CHROMEDRIVER_URL}...\"",
    "curl -# -Lo /tmp/chromedriver_linux64.zip \"${CHROMEDRIVER_URL}\"",
    "echo 'SETUP_CMDS: Unzipping Chromedriver...'",
    "sudo unzip -o /tmp/chromedriver_linux64.zip -d /tmp/chromedriver_extracted_temp",
    "echo 'SETUP_CMDS: Moving Chromedriver to /usr/local/bin/...'",
    
    # This entire 'sh -c ...' command is a single element in the TOML cmds array.
    # The shell script within the single quotes '...' uses actual newlines for clarity and command separation.
    """sh -c '
if [ -f /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver ]; then
  echo "SETUP_CMDS: Found chromedriver in chromedriver-linux64 subdirectory."
  sudo mv /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
elif [ -f /tmp/chromedriver_extracted_temp/chromedriver ]; then
  echo "SETUP_CMDS: Found chromedriver at the root of the extracted temp directory."
  sudo mv /tmp/chromedriver_extracted_temp/chromedriver /usr/local/bin/chromedriver
else
  echo "SETUP_CMDS: ERROR - chromedriver executable not found in expected zip structure!"
  echo "SETUP_CMDS: Listing contents of /tmp/chromedriver_extracted_temp/ for debugging:"
  ls -lR /tmp/chromedriver_extracted_temp
  exit 1
fi
'""",
    "sudo chmod +x /usr/local/bin/chromedriver",
    "rm -rf /tmp/chromedriver_extracted_temp /tmp/chromedriver_linux64.zip",
    "echo 'SETUP_CMDS: Chromedriver manually installed. Details:'",
    "/usr/local/bin/chromedriver --version"
  ]

[phases.install]
  # Default pip install command for your Python requirements
  cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
  # Your application's normal start command
  cmd = "python scrape.py"