# nixpacks.toml

[phases.setup]
  aptPkgs = [
    "chromium-browser",    # Installs the browser itself
    "curl", "unzip",       # Utilities for downloading and unzipping
    # Essential libraries for chromium-browser (keep your existing comprehensive list)
    "libglib2.0-0", "libnss3", "libfontconfig1", "libx11-6", "libxcb1",
    "libxcomposite1", "libxrandr2", "libxrender1", "libxtst6", "ca-certificates",
    "fonts-liberation", "libasound2t64", "libatk-bridge2.0-0", "libatk1.0-0",
    "libcups2", "libdbus-1-3", "libgdk-pixbuf2.0-0", "libgtk-3-0",
    "libpango-1.0-0", "libpangocairo-1.0-0", "xdg-utils"
    # Ensure "chromium-chromedriver" is NOT listed here from apt, to avoid conflicts.
  ]
  cmds = [
    "echo 'SETUP_CMDS: Starting manual Chromedriver installation...'",
    # Using a known recent stable Chromedriver version (e.g., for Chrome/Chromium 125)
    "CHROMEDRIVER_VERSION='125.0.6422.76'",
    "CHROMEDRIVER_URL='https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.76/linux64/chromedriver-linux64.zip'",
    "echo \"SETUP_CMDS: Downloading Chromedriver v${CHROMEDRIVER_VERSION} from ${CHROMEDRIVER_URL}...\"",
    "curl -# -Lo /tmp/chromedriver_linux64.zip \"${CHROMEDRIVER_URL}\"",
    "echo 'SETUP_CMDS: Unzipping Chromedriver...'",
    "sudo unzip -o /tmp/chromedriver_linux64.zip -d /tmp/chromedriver_extracted_temp",
    "echo 'SETUP_CMDS: Moving Chromedriver to /usr/local/bin/...'",
    # The zip for official chromedriver often contains a 'chromedriver-linux64' directory
    "if [ -f /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver ]; then \
      sudo mv /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver; \
    elif [ -f /tmp/chromedriver_extracted_temp/chromedriver ]; then \
      # Some older zips might have it at the root
      sudo mv /tmp/chromedriver_extracted_temp/chromedriver /usr/local/bin/chromedriver; \
    else \
      echo 'SETUP_CMDS: ERROR - chromedriver executable not found in expected zip structure! Listing contents:'; ls -lR /tmp/chromedriver_extracted_temp; exit 1; \
    fi",
    "sudo chmod +x /usr/local/bin/chromedriver",
    "rm -rf /tmp/chromedriver_extracted_temp /tmp/chromedriver_linux64.zip",
    "echo 'SETUP_CMDS: Chromedriver manually installed. Verifying version:'",
    "/usr/local/bin/chromedriver --version" # This will print the installed chromedriver version to deploy logs
  ]

[phases.install]
  # Default pip install command for your Python requirements
  cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
  # Your application's normal start command
  cmd = "python scrape.py"