# nixpacks.toml

#[phases.install]
# This command will run *before* Nixpacks tries to install your requirements.txt
#cmds_prepend = ["python -m pip install --upgrade pip setuptools wheel"]
# In your nixpacks.toml
#[start]
  cmd = "/usr/bin/chromium-browser --version && echo 'Chromium version printed above. Sleeping for 5 minutes...' && sleep 300"

[phases.setup]
  aptPkgs = [
    # Use Chromium browser and its chromedriver from Ubuntu's repositories
    "chromium-browser",
    "chromium-chromedriver",

    # Essential libraries for Chromium/Chromedriver
    "libglib2.0-0",
    "libnss3",
    "libfontconfig1",
    "libx11-6",
    "libxcb1",
    "libxcomposite1",
    "libxrandr2",
    "libxrender1",
    "libxtst6",

    # For HTTPS and fonts
    "ca-certificates",
    "fonts-liberation",

    # Additional libraries (using libasound2t64 for Ubuntu Noble)
    "libasound2t64",          # Explicitly use the t64 version for sound
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libcups2",
    "libdbus-1-3",
    "libgdk-pixbuf2.0-0",
    "libgtk-3-0",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "xdg-utils"
  ]
