# nixpacks.toml

[phases.install]
# This command will run *before* Nixpacks tries to install your requirements.txt
cmds_prepend = ["python -m pip install --upgrade pip setuptools wheel"]


# This section defines custom build phases.
[phases.setup]
  # 'aptPkgs' lists Debian/Ubuntu packages to install before your application builds.
  # These are crucial for running headless Chrome with Selenium.
  aptPkgs = [
    # Google Chrome browser
    "google-chrome-stable",

    # Essential libraries for Chrome/Chromedriver
    "libglib2.0-0",
    "libnss3",
    "libfontconfig1",
    "libx11-6",
    "libxcb1",
    "libxcomposite1",
    "libxrandr2",
    "libxrender1",
    "libxtst6",

    # For HTTPS and fonts
    "ca-certificates",
    "fonts-liberation",

    # Additional libraries often required for headless Browse and UI-related tasks
    "libasound2",             # For audio, can be required by some browser features
    "libatk-bridge2.0-0",     # Accessibility
    "libatk1.0-0",
    "libcups2",               # Printing, sometimes linked
    "libdbus-1-3",
    "libgdk-pixbuf2.0-0",     # Image loading
    "libgtk-3-0",             # Core GTK libraries, parts may be needed even headless
    "libpango-1.0-0",         # Text layout
    "libpangocairo-1.0-0",    # Pango with Cairo rendering
    "xdg-utils"               # Desktop integration utilities
  ]