# nixpacks.toml

[providers]
  python = "3.12" # Or your specified Python version

[phases.setup]
  aptPkgs = [
    "chromium-browser", # Installs the browser
    "curl", "unzip",     # Utilities needed for downloading and unzipping
    # Essential libraries for chromium-browser (keep your existing list)
    "libglib2.0-0", "libnss3", "libfontconfig1", "libx11-6", "libxcb1",
    "libxcomposite1", "libxrandr2", "libxrender1", "libxtst6", "ca-certificates",
    "fonts-liberation", "libasound2t64", "libatk-bridge2.0-0", "libatk1.0-0",
    "libcups2", "libdbus-1-3", "libgdk-pixbuf2.0-0", "libgtk-3-0",
    "libpango-1.0-0", "libpangocairo-1.0-0", "xdg-utils"
    # IMPORTANT: Do NOT include "chromium-chromedriver" from aptPkgs if you install it manually below
  ]
  # These commands run after aptPkgs are installed.
  cmds = [
    "echo 'SETUP_CMDS: Manually installing a specific Chromedriver version...'",
    # !!! USER ACTION: Replace this URL with the correct, verified download URL for your chosen Chromedriver version !!!
    # Get it from https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json
    # Example (VERIFY AND UPDATE THIS URL):
    "CHROMEDRIVER_URL='https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.76/linux64/chromedriver-linux64.zip'",
    "echo \"SETUP_CMDS: Downloading Chromedriver from ${CHROMEDRIVER_URL}...\"",
    "curl -Lo /tmp/chromedriver_linux64.zip \"${CHROMEDRIVER_URL}\"",
    "echo 'SETUP_CMDS: Unzipping Chromedriver...'",
    # Using sudo because /usr/local/bin is system-owned. Unzip to a temp location first.
    "sudo unzip -o /tmp/chromedriver_linux64.zip -d /tmp/chromedriver_extracted_temp",
    # The zip usually contains a directory like 'chromedriver-linux64', then 'chromedriver' inside it.
    "echo 'SETUP_CMDS: Moving Chromedriver to /usr/local/bin/...'",
    "if [ -f /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver ]; then \
      sudo mv /tmp/chromedriver_extracted_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver; \
    elif [ -f /tmp/chromedriver_extracted_temp/chromedriver ]; then \
      sudo mv /tmp/chromedriver_extracted_temp/chromedriver /usr/local/bin/chromedriver; \
    else \
      echo 'SETUP_CMDS: ERROR - chromedriver executable not found in expected zip structure!'; exit 1; \
    fi",
    "sudo chmod +x /usr/local/bin/chromedriver",
    "rm -rf /tmp/chromedriver_extracted_temp /tmp/chromedriver_linux64.zip",
    "echo 'SETUP_CMDS: Chromedriver manually installed. Details:'",
    "/usr/local/bin/chromedriver --version" # Verify installation
  ]

[phases.install]
  # Default pip install command
  cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
  # Your application's normal start command
  cmd = "python scrape.py"